version: '3.8'
services:
  app:
    build: .
    ports:
      - '4444:4444'
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/product-management-api # Use 'mongo' as the service name
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
