name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t achrefbechane34/product_management_api:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/product_management_api:latest
      - name: Deploy to Remote Server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          # Create the .ssh directory and set the right permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Step 1: Store the SSH key in a file and set the right permissions
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Step 2: SSH into the remote server and deploy the container
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@16.171.11.110 << 'EOF'
            # Login to Docker on the server
            docker login -u $DOCKERHUB_USERNAME -p ${{ secrets.DOCKERHUB_PASSWORD }}
            # clone github repo
            
            git clone https://github.com/achref2001/Product-Management-API.git /home/ec2-user/achref  
            cd /home/ec2-user/achref 
            git pull origin master
            docker-compose pull
            docker-compose  up -d


            # Pull the latest Docker image from Docker Hub
            # docker pull achrefbechane34/product_management_api:latest
            
            # Stop and remove any existing container with the same name
            # docker stop product_management_api || true
            # docker rm product_management_api || true
            
            # Run the new container
            # docker run -d --name product_management_api -p 4444:4444 --network achrefapp -e MONGODB_URI=mongodb://mongodb:27017/product-management-api achrefbechane34/product_management_api:latest
          EOF
       
